apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: false
    version: 1
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: "POST" 