# Docker Compose Override for Local Development
# This file is automatically loaded by docker-compose
# Use this for development-specific configurations

version: '3.8'

services:
  # Override for local development
  agentcare:
    volumes:
      - ./backend/src:/app/backend/src
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=agentcare:*
    command: npm run dev:backend

  # Override PostgreSQL for development
  postgres:
    environment:
      - POSTGRES_PASSWORD=dev_password_123
    ports:
      - "5432:5432"  # Expose for external tools

  # Override Redis for development  
  redis:
    ports:
      - "6379:6379"  # Expose for external tools

  # Override Ollama for development
  ollama:
    environment:
      - OLLAMA_DEBUG=true
    ports:
      - "11434:11434"  # Expose for external access 