global:
  environment: development

image:
  repository: node
  tag: "18-alpine"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 31780

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
          service:
            name: agentcare
            port:
              number: 3000

env:
  NODE_ENV: development
  API_PORT: "3000"
  LOG_LEVEL: debug
  ENABLE_OLLAMA_LLM: "true"
  ENABLE_RAG_SYSTEM: "true"
  ENABLE_USER_REGISTRATION: "true"
  HIPAA_LOGGING: "true"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"

postgresql:
  enabled: true
  primary:
    persistence:
      size: 1Gi
    service:
      type: NodePort
      port: 5432
      nodePort: 31820
  auth:
    database: agentcare
    username: agentcare_user

redis:
  enabled: true
  master:
    persistence:
      size: 1Gi
    service:
      type: NodePort
      port: 6379
      nodePort: 31830
  auth:
    enabled: true
  replica:
    replicaCount: 0

monitoring:
  prometheus:
    enabled: true
    server:
      persistentVolume:
        enabled: false
      service:
        type: NodePort
        port: 9090
        nodePort: 31790
    alertmanager:
      service:
        type: NodePort
        port: 9093
        nodePort: 31791
    pushgateway:
      service:
        type: NodePort
        port: 9091
        nodePort: 31792
    nodeExporter:
      service:
        type: NodePort
        port: 9100
        nodePort: 31793
  grafana:
    enabled: true
    persistence:
      enabled: false
    service:
      type: NodePort
      port: 3001
      nodePort: 31800
    adminPassword: admin123

tracing:
  jaeger:
    enabled: true
    allInOne:
      enabled: true
      service:
        type: NodePort
        port: 16686
        nodePort: 31810
    collector:
      enabled: true
      service:
        type: NodePort
        port: 14268
        nodePort: 31811
    agent:
      enabled: false
    query:
      enabled: false
    storage:
      type: memory

logging:
  loki:
    enabled: false
  promtail:
    enabled: false

development:
  enabled: true
  debugMode: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

command: ["node"]
args: ["/app/server.js"]

volumeMounts:
  - name: app-code
    mountPath: /app

volumes:
  - name: app-code
    configMap:
      name: agentcare-app

# Frontend Configuration
frontend:
  replicaCount: 1
  image:
    repository: node
    tag: "18-alpine"
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 80
    nodePort: 31781
  
  env:
    apiUrl: "http://localhost:31780"
    environment: "development" 