# Logstash Configuration for AgentCare Development
# Settings for log processing pipeline

# Node Configuration
node.name: agentcare-logstash
path.data: /usr/share/logstash/data
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# Pipeline Configuration
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# HTTP API Configuration
http.host: "0.0.0.0"
http.port: 9600

# Monitoring Configuration
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Log Configuration
log.level: info
log.format: plain

# Performance Settings
config.reload.automatic: true
config.reload.interval: 3s

# Dead Letter Queue
dead_letter_queue.enable: false

# Queue Configuration
queue.type: memory
queue.max_events: 0
queue.max_bytes: 1gb 