# AgentCare Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration (disabled by default)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files (disabled by default)
rule_files: []

# Scrape configurations
scrape_configs:
  # Backend API metrics
  - job_name: 'agentcare-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:9090']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 