apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentcare.fullname" . }}-config
  labels:
    {{- include "agentcare.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  API_PORT: {{ .Values.env.API_PORT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  ENABLE_OLLAMA_LLM: {{ .Values.env.ENABLE_OLLAMA_LLM | quote }}
  ENABLE_RAG_SYSTEM: {{ .Values.env.ENABLE_RAG_SYSTEM | quote }}
  ENABLE_USER_REGISTRATION: {{ .Values.env.ENABLE_USER_REGISTRATION | quote }}
  HIPAA_LOGGING: {{ .Values.env.HIPAA_LOGGING | quote }}
  ENABLE_METRICS: {{ .Values.env.ENABLE_METRICS | quote }}
  ENABLE_TRACING: {{ .Values.env.ENABLE_TRACING | quote }}
  REDIS_URL: "redis://{{ .Release.Name }}-redis-master:6379"
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:$(POSTGRES_PASSWORD)@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  OLLAMA_BASE_URL: "http://{{ .Release.Name }}-ollama:11434" 