apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "agentcare.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "agentcare.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "agentcare.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      volumes:
        - name: frontend-config
          configMap:
            name: {{ .Release.Name }}-frontend-config
      containers:
        - name: frontend
          image: "nginx:alpine"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: frontend-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.frontend.env.apiUrl | quote }}
            - name: REACT_APP_ENV
              value: {{ .Values.frontend.env.environment | quote }} 