apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentcare.fullname" . }}-secret
  labels:
    {{- include "agentcare.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwt.secret }}
  JWT_SECRET: {{ .Values.secrets.jwt.secret | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.session.secret }}
  SESSION_SECRET: {{ .Values.secrets.session.secret | b64enc | quote }}
  {{- else }}
  SESSION_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.encryption.key }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryption.key | b64enc | quote }}
  {{- else }}
  ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | default (randAlphaNum 16) | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | default (randAlphaNum 16) | b64enc | quote }} 