# AgentCare Documentation Site Configuration
title: "AgentCare Documentation"
description: >-
  AI-powered healthcare scheduling platform with multi-agent coordination,
  HIPAA compliance, and real-time appointment management.

baseurl: "/agentcare"
url: "https://vishalm.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme
remote_theme: pages-themes/cayman@v0.2.0

# Site logo and favicon
logo: "/agentcare/docs/assets/images/agentcare-logo-square.svg"
favicon: "/agentcare/docs/assets/images/favicon-32x32.png"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-relative-links

# Mermaid configuration
mermaid:
  version: "10.6.1"
  theme: "default"

# GitHub repository
repository: vishalm/agentcare

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - LICENSE 