# Elasticsearch Configuration for AgentCare Development
# Optimized for log storage and search performance

# Cluster Configuration
cluster.name: agentcare-dev
node.name: agentcare-node-1
node.roles: [ master, data, ingest ]

# Network Configuration
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery Configuration
discovery.type: single-node
discovery.seed_hosts: []

# Path Configuration
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory Configuration
bootstrap.memory_lock: false
indices.memory.index_buffer_size: 10%
indices.memory.min_index_buffer_size: 48mb

# Index Configuration
action.destructive_requires_name: false

# Security Configuration (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Monitoring Configuration
xpack.monitoring.collection.enabled: true
xpack.monitoring.elasticsearch.collection.enabled: false

# Index Lifecycle Management
xpack.ilm.enabled: true

# Performance Settings
indices.queries.cache.size: 10%
indices.fielddata.cache.size: 15%
indices.requests.cache.size: 1%

# Thread Pool Configuration
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# Logging Configuration
logger.level: INFO
logger.org.elasticsearch.deprecation: WARN

# Development Settings
action.auto_create_index: "+agentcare-*,-*"
cluster.routing.allocation.disk.watermark.low: 95%
cluster.routing.allocation.disk.watermark.high: 97%
cluster.routing.allocation.disk.watermark.flood_stage: 99% 